/**
 * PLACEHOLDER SYSTEM FOR CERTIFICATE / ADMIT CARD BUILDER
 * ─────────────────────────────────────────────────────────
 * Central registry of all dynamic placeholders used in template builder.
 * Each placeholder maps to a real data field during generation.
 *
 * HOW IT WORKS:
 * 1. Builder stores placeholders as {{key}} in element content
 * 2. During generation, the API replaces {{key}} with actual student/school data
 * 3. Image-type placeholders (schoolLogo, studentPhoto, etc.) are replaced with URLs
 *
 * ADDING NEW PLACEHOLDERS:
 * 1. Add the entry below with key, label, category, type, description, example
 * 2. Update the generation API to map the key to actual data
 */

export const PLACEHOLDER_CATEGORIES = [
    {
        id: 'student',
        label: '👤 Student',
        icon: 'User',
        placeholders: [
            { value: 'student_name', label: 'Student Name', type: 'text', description: 'Full name of the student', example: 'Rahul Sharma' },
            { value: 'father_name', label: 'Father Name', type: 'text', description: "Student's father name", example: 'Rajesh Sharma' },
            { value: 'mother_name', label: 'Mother Name', type: 'text', description: "Student's mother name", example: 'Priya Sharma' },
            { value: 'dob', label: 'Date of Birth', type: 'text', description: 'Date of birth (formatted)', example: '15-Jan-2010' },
            { value: 'gender', label: 'Gender', type: 'text', description: 'Male / Female / Other', example: 'Male' },
            { value: 'roll_number', label: 'Roll Number', type: 'text', description: 'Class roll number', example: '25' },
            { value: 'admission_number', label: 'Admission Number', type: 'text', description: 'Unique admission number', example: 'ADM-2024-0042' },
            { value: 'studentPhoto', label: 'Student Photo', type: 'image', description: 'Passport size photo of student', example: '' },
            { value: 'address', label: 'Address', type: 'text', description: 'Full residential address', example: '123 MG Road, New Delhi' },
            { value: 'bloodGroup', label: 'Blood Group', type: 'text', description: 'Blood group', example: 'B+' },
            { value: 'studentId', label: 'Student ID', type: 'text', description: 'System student ID', example: 'STU-00042' },
        ]
    },
    {
        id: 'academic',
        label: '🏫 Academic',
        icon: 'BookOpen',
        placeholders: [
            { value: 'class', label: 'Class', type: 'text', description: 'Current class/grade', example: '10th' },
            { value: 'section', label: 'Section', type: 'text', description: 'Section name', example: 'A' },
            { value: 'session', label: 'Session', type: 'text', description: 'Academic session/year', example: '2025-26' },
            { value: 'stream', label: 'Stream', type: 'text', description: 'Academic stream (Science/Commerce/Arts)', example: 'Science' },
        ]
    },
    {
        id: 'certificate',
        label: '🧾 Certificate',
        icon: 'Award',
        placeholders: [
            { value: 'certificate_id', label: 'Certificate ID', type: 'text', description: 'Unique certificate number', example: 'CERT-2026-00142' },
            { value: 'issue_date', label: 'Issue Date', type: 'text', description: 'Date of issuance', example: '02-Apr-2026' },
            { value: 'generated_by', label: 'Generated By', type: 'text', description: 'Name of the issuing authority', example: 'Admin Office' },
            { value: 'verificationUrl', label: 'Verification URL', type: 'text', description: 'URL for QR verification', example: 'https://edubreezy.com/verify/CERT-2026-00142' },
            { value: 'validUntil', label: 'Valid Until', type: 'text', description: 'Expiry / validity date', example: '31-Mar-2027' },
        ]
    },
    {
        id: 'school',
        label: '🏫 School',
        icon: 'School',
        placeholders: [
            { value: 'school_name', label: 'School Name', type: 'text', description: 'Full school name', example: 'Bright Future School' },
            { value: 'school_address', label: 'School Address', type: 'text', description: 'School address', example: '456 Education Lane, Mumbai' },
            { value: 'schoolLogo', label: 'School Logo', type: 'image', description: 'School logo image', example: '' },
            { value: 'schoolStamp', label: 'School Stamp', type: 'image', description: 'Official school stamp image', example: '' },
            { value: 'principalSignature', label: 'Principal Signature', type: 'image', description: "Principal's signature image", example: '' },
            { value: 'classTeacherSignature', label: 'Class Teacher Signature', type: 'image', description: "Class teacher's signature image", example: '' },
        ]
    },
    {
        id: 'exam',
        label: '📝 Exam',
        icon: 'ClipboardList',
        placeholders: [
            { value: 'exam_name', label: 'Exam Name', type: 'text', description: 'Name of the exam', example: 'Annual Examination 2026' },
            { value: 'exam_date', label: 'Exam Date', type: 'text', description: 'Date of exam', example: '15-Mar-2026' },
            { value: 'examCenter', label: 'Exam Center', type: 'text', description: 'Center / venue name', example: 'Main Hall' },
            { value: 'center_name', label: 'Center Name', type: 'text', description: 'Alternate center name field', example: 'Center A' },
            { value: 'room_number', label: 'Room Number', type: 'text', description: 'Room/hall number', example: 'Room 12' },
            { value: 'seatNumber', label: 'Seat Number', type: 'text', description: 'Assigned seat number', example: '42' },
            { value: 'examSchedule', label: 'Exam Schedule', type: 'text', description: 'Schedule description', example: '10:00 AM - 1:00 PM' },
        ]
    },
];

/**
 * Flattened list of all placeholders for backward compatibility.
 * Use this in components that need a simple array.
 */
export const ALL_PLACEHOLDERS = PLACEHOLDER_CATEGORIES.flatMap(cat =>
    cat.placeholders.map(ph => ({
        ...ph,
        category: cat.id,
        categoryLabel: cat.label,
    }))
);

/**
 * Get only image-type placeholders (for image element source dropdown)
 */
export const IMAGE_PLACEHOLDERS = ALL_PLACEHOLDERS.filter(ph => ph.type === 'image');

/**
 * Get only text-type placeholders (for text/dynamic field elements)
 */
export const TEXT_PLACEHOLDERS = ALL_PLACEHOLDERS.filter(ph => ph.type === 'text');

/**
 * Legacy format — maps to the old { value, label } format used in create/edit pages
 */
export const LEGACY_PLACEHOLDERS = ALL_PLACEHOLDERS.map(ph => ({
    value: ph.value,
    label: ph.label,
}));
