DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'CheckoutType') THEN
    CREATE TYPE "CheckoutType" AS ENUM ('MANUAL', 'AUTO', 'EXTENDED_AUTO');
  END IF;
END $$;

ALTER TABLE "Attendance"
  ADD COLUMN IF NOT EXISTS "overtimeHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "overtimeStatus" "ApprovalStatus" NOT NULL DEFAULT 'NOT_REQUIRED',
  ADD COLUMN IF NOT EXISTS "overtimeApprovedBy" UUID,
  ADD COLUMN IF NOT EXISTS "overtimeApprovedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "overtimeApprovalRemarks" TEXT,
  ADD COLUMN IF NOT EXISTS "checkoutType" "CheckoutType" NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS "isExtended" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "extendedTill" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "extensionRequestedAt" TIMESTAMP(3);

ALTER TABLE "AttendanceConfig"
  ADD COLUMN IF NOT EXISTS "autoCheckoutBufferMinutes" INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS "maxExtensionHours" DOUBLE PRECISION NOT NULL DEFAULT 4;

ALTER TABLE "PayrollConfig"
  ADD COLUMN IF NOT EXISTS "includeOvertimeInPayroll" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "overtimeRequiresApproval" BOOLEAN NOT NULL DEFAULT true;
