import { NextResponse } from "next/server";
import { z } from "zod";
import prisma from "@/lib/prisma";
import { supabaseAdmin } from "@/lib/supbase-admin";
import { delCache } from "@/lib/cache";


const createUserSchema = z.object({
    role: z.enum(["LIBRARIAN", "ACCOUNTANT"]),
    email: z.string().email(),
    password: z.string().transform(val => val === "" ? undefined : val).optional().refine(val => !val || val.length >= 6, {
        message: "Password must be at least 6 characters if provided"
    }),
    name: z.string(),
    schoolId: z.string().uuid(),
    permissions: z.record(z.boolean()).optional(),
});

// Helper function to generate random password
function generatePassword() {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%";
    let password = "";
    for (let i = 0; i < 12; i++) {
        password += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return password;
}

export async function POST(req) {
    try {
        const body = await req.json();
        const data = createUserSchema.parse(body);
        console.log(data);

        if (!data.schoolId) {
            return NextResponse.json(
                { error: "School ID is required" },
                { status: 400 }
            );
        }
        // Step 1: Generate password if not provided
        const password = data.password || generatePassword();

        // Step 2: Check if role exists, if not create it
        let role = await prisma.role.findUnique({
            where: { name: data.role },
        });

        if (!role) {
            role = await prisma.role.create({
                data: { name: data.role },
            });
        }

        // Step 3: Create user in Supabase
        const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
            email: data.email,
            password,
            email_confirm: true,
            user_metadata: {
                name: data.name,
                role: data.role,
            },
        });

        if (authError || !authData.user) {
            return NextResponse.json(
                { error: "Failed to create user in Supabase", details: authError?.message },
                { status: 400 }
            );
        }

        // Step 4: Create user in Prisma
        const user = await prisma.user.create({
            data: {
                id: authData.user.id,
                email: data.email,
                password: password,
                name: data.name,
                roleId: role.id,
                schoolId: data.schoolId,
                status: "ACTIVE",
            },
        });

        // Step 5: Create role-specific record (Librarian or Accountant)
        if (data.role === "LIBRARIAN") {
            await prisma.librarian.create({
                data: {
                    userId: user.id,
                    schoolId: data.schoolId,
                    permissions: data.permissions || {},
                },
            });

            // Invalidate librarians cache
            await delCache("librarians:all");
        } else if (data.role === "ACCOUNTANT") {
            await prisma.accountant.create({
                data: {
                    userId: user.id,
                    schoolId: data.schoolId,
                    permissions: data.permissions || {},
                },
            });

            // Invalidate accountants cache
            await delCache("accountants:all");
        }

        // Step 6: Return success with login credentials
        return NextResponse.json({
            success: true,
            user: {
                id: user.id,
                email: user.email,
                name: user.name,
                role: data.role,
            },
            credentials: {
                email: data.email,
                password: password,
                autoGenerated: !data.password,
            },
        });
    } catch (err) {
        console.error("Create user error:", err);

        if (err instanceof z.ZodError) {
            return NextResponse.json(
                { error: "Validation error", details: err.errors },
                { status: 400 }
            );
        }

        return NextResponse.json(
            {
                error: "Internal Server Error",
                message: err instanceof Error ? err.message : String(err),
            },
            { status: 500 }
        );
    }
}
